# coding: utf8
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['hstwb-installer.py']
DATA_FILES = ['hstwb-installer.ico']
OPTIONS = {
  'iconfile': 'hstwb-installer.icns',
  'plist': {
        'CFBundleName': "HstWB Installer",
        'CFBundleDisplayName': "HstWB Installer",
        'CFBundleGetInfoString': "HstWB Installer automates installation of Workbench",
        'CFBundleIdentifier': "com.firstrealize.hstwbinstaller",
        'CFBundleVersion': "2.0.0",
        'CFBundleShortVersionString': "2.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2018, Henrik Nørfjand Stengaard"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
